log:
  level: INFO

api:
  dashboard: true
  insecure: false

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: selfsigned

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
