spring.datasource.url=jdbc:postgresql://db:5432/ma_base
spring.datasource.username=postgres
spring.datasource.password=monpasswordsolide

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

app.frontend.url=http://localhost:5173
brevo.api.key=${BREVO_API_KEY:}
gemini.api.key=${GEMINI_API_KEY:}
